PKG_NAME=sphss
PKG_URL=https://github.com/gbanegas/sphss.git
PKG_VERSION=037102d3138e43e8784418679a721d8b81fed309
PKG_LICENSE=Apache-2.0

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR) -f $(CURDIR)/$(PKG_NAME).mk
